### ISSUE TITLE
Idioma sólo se puede cambiar una vez

### ISSUE THREAD

**Issue by jcao02** [zomoz/reportes#11]
## Estoy reportando...

- [x] Error 
- [ ] Mejora 
- [ ] Métrica 
- [ ] Otro... Por favor descríbelo:

## Comportamiento actual
Video que explica lo que ocurre: https://www.useloom.com/share/48be01b71b944ee59f8bd7529f6a0ad5

## Comportamiento esperado
Se deberia cambiar el idioma de la página con normalidad

## ¿Qué impacto tiene en el negocio este reporte? 

- [ ] Bloqueante 
- [ ] Impacto nivel 3 
- [x] Impacto nivel 2 
- [ ] Impacto nivel 1 

## Instrucciones para replicar el problema 
Ver el video que está en la sección de **Comportamiento actual**

**Comment by MichelleFernandez** [comment]
En producción
