### ISSUE TITLE
Se crean espacios grises en la galería entre foto y foto

### ISSUE THREAD

**Issue by jcao02** [zomoz/reportes#14]
## Estoy reportando...

- [x] Error 
- [ ] Mejora 
- [ ] Métrica 
- [ ] Otro... Por favor descríbelo:

## Comportamiento actual
![image](https://user-images.githubusercontent.com/2745307/39002861-7c40f1a2-43c7-11e8-8235-ffac3b0a446b.png)

## Comportamiento esperado
Que no aparezcan las rayas

## ¿Qué impacto tiene en el negocio este reporte? 

- [ ] Bloqueante 
- [x] Impacto nivel 3 
- [ ] Impacto nivel 2 
- [ ] Impacto nivel 1 

## Instrucciones para replicar el problema 
Con abrir una actividad es suficiente

## Ambiente para replicar 

Browser:
- [x] Chrome versión 63
- [ ] Firefox versión XX
- [ ] Safari versión XX
- [ ] IE versión XX
- [ ] Edge versión XX
 
Plataforma:
- [x] Windows 10
- [ ] Linux:  
- [ ] Mac XX
- [ ] iOS XX
- [ ] Android XX
- [ ] Windows Phone XX

Otros:

**Comment by chamini2** [comment]
@FranMonteverde, ¿puedes pasar un video de esto sucediendo?

**Comment by FranMonteverde** [comment]
@chamini2 sorry! No tenía GitBug Notifier y no sabía que me habías escrito. 

Por algún motivo esto se "solucionó" aunque creo que mejor diría "mitigó" - Ahora las rayas son mucho menores. Esas rayas enormes ya no están apareciendo. Ahorita lo que vas a conseguir son unas rayitas pequeñas básicamente todas del mismo tamaño. 

Si me gustaría que se viese super calidad como creo que se ve en iOS que esas rayas no aparecen del todo. Sin dado Paso a Impacto 1 pero no lo considero resuelto. Te mando un video para que veas las rayitas. 

https://www.useloom.com/share/a5117c8721ef4913a33c34a08ff91edf

**Comment by chamini2** [comment]
Como puedes ver en https://app.zeplin.io/project/579bc8e3cb0154a84c5ab425/screen/596e205a3885197abbb25c19, es de diseño el tema del separador.

**Comment by FranMonteverde** [comment]
@chamini2 excelente! Issue cerrado entonces
