### ISSUE TITLE
El detalle en las calificaciones es demasiado amplio - Muestra N decimales 

### ISSUE THREAD

**Issue by FranMonteverde** [zomoz/reportes#19]
## Estoy reportando...

- [x] Error 
- [ ] Mejora 
- [ ] Métrica 
- [ ] Otro... Por favor descríbelo:

## Comportamiento actual
La plataforma está mostrando un exceso de decimales en el total de los reviews. 
![image](https://user-images.githubusercontent.com/38536200/39006667-5d184d1e-43c9-11e8-842c-12b3e2af94f7.png)

## Comportamiento esperado
Los reviews deberían mostrar únicamente un decimal. Ejemplo 4,4 - En el caso que vemos, el número que le sigue es 6 (4,46) - Por lo que idealmente deberíamos rodeandear para arriba cuando =>5
En este caso, el resultado final debería ser 4,5

## ¿Cuál es la motivación / caso de uso para este reporte?  
Las calificaciones no requieren de tanto detalle y actualmente muestran una falta de profesionalismo en como se muestra la información. Es un detalle innecesario. Calificaciones son la consideración #1 a la hora de comprarlificaciones no requieren de tanto detalle y actualmente muestran una falta de profesionalismo en como se muestra la información. Es un detalle innecesario. Calificaciones son la consideración #1 a la hora de comprar

## ¿Qué impacto tiene en el negocio este reporte? 

- [ ] Bloqueante 
- [x] Impacto nivel 3 
- [ ] Impacto nivel 2 
- [ ] Impacto nivel 1 

## Instrucciones para replicar el problema 

Tan con con entrar a la siguiente actividad - https://zomoz.travel/co/activities/2279 - se puede ver el error con mucha facilidad

## Ambiente para replicar 

User-agent: 

Browser:
- [ ] Chrome versión XX
- [ ] Firefox versión XX
- [ ] Safari versión XX
- [ ] IE versión XX
- [ ] Edge versión XX
 
Plataforma:
- [ ] Windows XX
- [ ] Linux:  
- [ ] Mac XX
- [ ] iOS XX
- [ ] Android XX
- [ ] Windows Phone XX

Otros:

****

**Comment by jcao02** [comment]
@testica crees poder hacer esto?

**Comment by testica** [comment]
@jcao02 plomo

**Comment by testica** [comment]
@FranMonteverde bro, recuerda poner algún enlace a staging o forma de replicarlo

**Comment by FranMonteverde** [comment]
@testica mostro! Demasiado raro... lo hice 100% - Tiene que haber sido que escribí donde no era en la sección de - Instrucciones para replicar el problema - y no se pasó la info. Mala mía! 

Es una papaya. Aquí tienes la actividad de donde saco la foto 

https://zomoz.travel/co/activities/2279
