### ISSUE TITLE
Botón de Nosotros en el Home está roto 

### ISSUE THREAD

**Issue by FranMonteverde** [zomoz/reportes#23]
## Estoy reportando...

- [x] Error 
- [ ] Mejora 
- [ ] Métrica 
- [ ] Otro... Por favor descríbelo:

## Comportamiento actual

El botón de "nosotros" - Creo que dice Conócenos - en el home está roto 
![image](https://user-images.githubusercontent.com/38536200/39021702-8ed84e70-43f7-11e8-80bf-e0c9ab9cdeae.png)

## Comportamiento esperado

El botón no es blanco. Debería verse con su diseño completo

## ¿Cuál es la motivación / caso de uso para este reporte?  
 Lo considero un reporte Impacto 3 pues es nuestra apariencia y es el home, por lo que genera desconfianza ver un bug con tanta facilidad a un link que te invita a conocernos. Aparte, es una tarea extremadamente facil de resolver 

## ¿Qué impacto tiene en el negocio este reporte? 

- [ ] Bloqueante 
- [x] Impacto nivel 3 
- [ ] Impacto nivel 2 
- [ ] Impacto nivel 1 

## Instrucciones para replicar el problema 

Lo vi tanto en mi celular como en la computadora. Creo que va a ser sumamente sencillo de ubicar 
## Ambiente para replicar 

User-agent: 

Browser:
- [ ] Chrome versión XX
- [ ] Firefox versión XX
- [ ] Safari versión XX
- [ ] IE versión XX
- [ ] Edge versión XX
 
Plataforma:
- [ ] Windows XX
- [ ] Linux:  
- [ ] Mac XX
- [ ] iOS XX
- [ ] Android XX
- [ ] Windows Phone XX

Otros:

**Comment by jcao02** [comment]
@chamini2 parece ser una regresión de la eliminación del módulo de static. Podrías revisar?

**Comment by FranMonteverde** [comment]
@chamini2 @jcao02 cuando sale este Deployment? 5 Days ago un bug en el Home. 

Me parece mejor práctica no poner como "closed" los issues hasta que estén deployed. Avisen si no están de acuerdo

**Comment by chamini2** [comment]
Sale hoy, @FranMonteverde. Aunque de acuerdo en que no se debe cerrar hasta que esté _deployed_.
