### ISSUE TITLE
Cambiar los textos del menú

### ISSUE THREAD

**Issue by chamini2** [zomoz/reportes#29]
## Estoy reportando...

- [ ] Error 
- [x] Mejora 
- [ ] Métrica 
- [ ] Otro... Por favor descríbelo:

## Comportamiento actual

![image](https://user-images.githubusercontent.com/2745502/39061065-1f97e4c2-4491-11e8-95d2-8de4870eed03.png)

## Comportamiento esperado

Mis Planes ---> Mis Actividades
Crear Plan ---> Crear Actividad 
Beneficios: Anfitriones --- Tiene el link de unete.zomoz / Cambiar a info para que no tenga que redireccionar 

## ¿Cuál es la motivación / caso de uso para este reporte?  

¿Mantener la palabra «actividad» en todas partes?

## ¿Qué impacto tiene en el negocio este reporte? 

- [ ] Bloqueante 
- [ ] Impacto nivel 3 
- [x] Impacto nivel 2 
- [ ] Impacto nivel 1 

https://3.basecamp.com/3391686/buckets/1144986/todos/1013622601

**Comment by chamini2** [comment]
@FranMonteverde

**Comment by jcao02** [comment]
@chamini2 recuerda asignar los módulos

**Comment by FranMonteverde** [comment]
@chamini2 el link que tiene es unete.zomoz.travel - El link correcto es info.zomoz.travel 

Avísame cualquier cosa!

**Comment by chamini2** [comment]
Esto está listo! Apuntando a info.zomoz.travel correctamente.

**Comment by FranMonteverde** [comment]
@chamini2 Te mando un video porque la carga tiene un mega delay. Creo que es el tema de que si no haces scroll, no aparece la imagen. Siendo WIX aprovecho de mencionar a Atilio (no tiene GitBug) 

De igual forma, a nivel de bug si está solucionado pues está bien direccionado. 

https://www.useloom.com/share/d464e457f7d84354aa5822b0d09023ce

**Comment by chamini2** [comment]
Eso es a nivel del Wix, nada que podamos hacer desde cliente web. Podría revisar con @SofiKele, Atilio u Orlando.
