### ISSUE TITLE
Crear nuevo merge-tag para Sendgrid: "request_payment_total"

### ISSUE THREAD

**Issue by GabyVelu** [zomoz/reportes#31]
## Estoy reportando...

- [ ] Error 
- [x] Mejora 
- [ ] Métrica 
- [ ] Otro... Por favor descríbelo:

## Comportamiento actual
Actualmente en el correo de "Solicitud Aprobada" que le llega al cliente, tenemos una sección de información sobre la compra que acaba de realizar. En esta sección se le muestra: 1. El número de orden y 2. El total pagado. --> Para los casos que son de compras con cupón, el total pagado es distinto al precio de la actividad. Actualmente no tenemos un merge-tag que jale la información del monto pagado.

## Comportamiento esperado
Deberíamos tener dos merge-tags para cada información. Actualmente la necesitamos para este correo y a futuro la necesitaremos cuando querramos generar un recibo de compra más elaborado.

## ¿Cuál es la motivación / caso de uso para este reporte?  
El uso será en el correo de "Solicitud Aprobada" que le llega al cliente luego de que aprueban su solicitud de reserva. La idea es brindarle seguridad sobre la compra que acaba de realizar, le proveemos su número de orden + el monto total que pagó 
-->

## ¿Qué impacto tiene en el negocio este reporte? 

- [ ] Bloqueante 
- [ ] Impacto nivel 3 
- [ ] Impacto nivel 2 
- [x] Impacto nivel 1 

## Ambiente para replicar 

User-agent: 

Browser:
- [ ] Chrome versión XX
- [ ] Firefox versión XX
- [ ] Safari versión XX
- [ ] IE versión XX
- [ ] Edge versión XX
 
Plataforma:
- [ ] Windows XX
- [ ] Linux:  
- [ ] Mac XX
- [ ] iOS XX
- [ ] Android XX
- [ ] Windows Phone XX

Otros:

**Comment by chamini2** [comment]
Creando `%request_payment_total%`

**Comment by chamini2** [comment]
Listo, ya se puede usar.
