### ISSUE TITLE
Utilizar nueva ruta de Facebook desde cliente Android

### ISSUE THREAD

**Issue by chamini2** [zomoz/reportes#32]
## Estoy reportando...

- [ ] Error 
- [ ] Mejora 
- [ ] Métrica 
- [x] Otro... Por favor descríbelo:

## Comportamiento actual

Le pega a `POST /sessions/facebook`

## Comportamiento esperado

Debería pegarle a `POST /sessions/facebook/sign-in`

## ¿Cuál es la motivación / caso de uso para este reporte?  

Para quitar código deprecado del Backend

## ¿Qué impacto tiene en el negocio este reporte? 

- [ ] Bloqueante 
- [ ] Impacto nivel 3 
- [ ] Impacto nivel 2 
- [x] Impacto nivel 1

**Comment by testica** [comment]
Deployed!
