### ISSUE TITLE
Calificaciones del Perfil del Anfi están Rotas - Se muestran vacías

### ISSUE THREAD

**Issue by FranMonteverde** [zomoz/reportes#34]
## Estoy reportando...

- [x] Error 
- [ ] Mejora 
- [ ] Métrica 
- [ ] Otro... Por favor descríbelo:

## Comportamiento actual

Cuando se visita el perfil de un anfitrión, las estrellas salen siempre vacías (siempre y cuando tenga una calificación) - Ejemplo --- 
![image](https://user-images.githubusercontent.com/38536200/39146902-bcaa1424-46fd-11e8-8c6a-5d0422f3d5bd.png)

## Comportamiento esperado

El perfil debería mostrar las estrellas llenas según el resultado que haya obtenido el Anfi
## ¿Cuál es la motivación / caso de uso para este reporte?  

Las calificaciones es el elemento #1 a la hora de tomar una decisión de compra. Deben funcionar a la perfección
## ¿Qué impacto tiene en el negocio este reporte? 

- [ ] Bloqueante 
- [x] Impacto nivel 3 
- [ ] Impacto nivel 2 
- [ ] Impacto nivel 1 

## Instrucciones para replicar el problema 

Se puede ver en mucho perfiles. Aquí les dejo un par 
https://zomoz.travel/users/12627/gerardo-12627
https://zomoz.travel/users/12526

## Ambiente para replicar 

User-agent: 

Browser:
- [ ] Chrome versión XX
- [ ] Firefox versión XX
- [ ] Safari versión XX
- [ ] IE versión XX
- [ ] Edge versión XX
 
Plataforma:
- [ ] Windows XX
- [ ] Linux:  
- [ ] Mac XX
- [ ] iOS XX
- [ ] Android XX
- [ ] Windows Phone XX

Otros:

**Comment by jcao02** [comment]
@chamini2 o @testica alguno se puede encargar?

**Comment by testica** [comment]
activo @jcao02
