### ISSUE TITLE
Arreglar la ubicación de las reseñas en el detalle de la actividad

### ISSUE THREAD

**Issue by atilioferrando** [zomoz/reportes#44]
## Estoy reportando...

- [x] Error 
- [ ] Mejora 
- [ ] Métrica 
- [ ] Otro... Por favor descríbelo:

## Comportamiento actual

Las reseñas se muestran de último en el detalle de la actividad

## Comportamiento esperado

Que las reseñas se muestren antes de la sección del itinerario. Tal como esta en Zeplin
https://app.zeplin.io/project/579bc8e3cb0154a84c5ab425/screen/596e205a3885197abbb25c19

## ¿Qué impacto tiene en el negocio este reporte? 

- [ ] Bloqueante 
- [x] Impacto nivel 3 
- [ ] Impacto nivel 2 
- [ ] Impacto nivel 1 

## Ambiente para replicar 

User-agent: 

Browser:
- [ ] Chrome versión XX
- [ ] Firefox versión XX
- [ ] Safari versión XX
- [ ] IE versión XX
- [ ] Edge versión XX
 
Plataforma:
- [ ] Windows XX
- [ ] Linux:  
- [ ] Mac XX
- [ ] iOS XX
- [ ] Android XX
- [ ] Windows Phone XX

Otros:

**Comment by MichelleFernandez** [comment]
En producción
