### ISSUE TITLE
Mantener la misma vista que se solicitó al pedir iniciar sesión

### ISSUE THREAD

**Issue by FranMonteverde** [zomoz/reportes#52]
## Estoy reportando...

- [ ] Error 
- [x] Mejora 
- [ ] Métrica 
- [ ] Otro... Por favor descríbelo:

## Comportamiento actual

Cuando solicitas una acción que requiere tener un usuario (escribir en el chat por ejemplo) y estás sin iniciar sesion te manda a registrarte o iniciar sesión y luego de hacerlo no te abre la página que habías solicitado abrir

## Comportamiento esperado

Luego de registrarte o iniciar sesión, te debe abrir la vista que solicitaste abrir en primer momento 

## ¿Cuál es la motivación / caso de uso para este reporte?  

Que el usuario disfrute de una mejor navegación y experiencia de uso en la plataforma

## ¿Qué impacto tiene en el negocio este reporte? 

- [ ] Bloqueante 
- [ ] Impacto nivel 3 
- [x] Impacto nivel 2 
- [ ] Impacto nivel 1 

## Instrucciones para replicar el problema 

En el siguiente video pueden ver exactamente lo que pido. Lo idea es que luego de iniciar sesión, me abra la vista de enviar mensaje - https://www.useloom.com/share/31a33a27bf124feb81581cc565006004

## Ambiente para replicar 

User-agent: 

Browser:
- [ ] Chrome versión XX
- [ ] Firefox versión XX
- [ ] Safari versión XX
- [ ] IE versión XX
- [ ] Edge versión XX
 
Plataforma:
- [ ] Windows XX
- [ ] Linux:  
- [ ] Mac XX
- [ ] iOS XX
- [ ] Android XX
- [ ] Windows Phone XX

Otros:

**Comment by chamini2** [comment]
Duplicado de https://github.com/zomoz/reportes/issues/46
