### ISSUE TITLE
Algunas Monedas no caben en el Selector del Footer

### ISSUE THREAD

**Issue by FranMonteverde** [zomoz/reportes#53]
## Estoy reportando...

- [x] Error 
- [ ] Mejora 
- [ ] Métrica 
- [ ] Otro... Por favor descríbelo:

## Comportamiento actual

En Desktop, las monedas COP USD AUD no caben en el espacio del selector del footer

## Comportamiento esperado

Todo el texto de la moneda debería caber en el selector 

## ¿Cuál es la motivación / caso de uso para este reporte?  

Mejor experiencia del usuario y belleza en la plataforma 

## ¿Qué impacto tiene en el negocio este reporte? 

- [ ] Bloqueante 
- [ ] Impacto nivel 3 
- [ ] Impacto nivel 2 
- [x] Impacto nivel 1 

## Instrucciones para replicar el problema 

Lo pongo Impacto 1 pues no son demasiadas las personas que bajan al footer y que sufren este pain de verlo 
![image](https://user-images.githubusercontent.com/38536200/39410293-07047240-4bbc-11e8-93ad-f81a6696a2b0.png)

![image](https://user-images.githubusercontent.com/38536200/39410294-10a6d356-4bbc-11e8-8d6d-d3a45a73aee9.png)

## Ambiente para replicar 

User-agent: 

Browser:
- [ ] Chrome versión XX
- [ ] Firefox versión XX
- [ ] Safari versión XX
- [ ] IE versión XX
- [ ] Edge versión XX
 
Plataforma:
- [ ] Windows XX
- [ ] Linux:  
- [ ] Mac XX
- [ ] iOS XX
- [ ] Android XX
- [ ] Windows Phone XX

Otros:

**Comment by testica** [comment]
Le pondré un ancho de 230px. Antes estaba en 180px @FranMonteverde

**Comment by FranMonteverde** [comment]
Sin problema! Si cabe USD que es la mas larga, estamos issue closed @testica

**Comment by testica** [comment]
@FranMonteverde que tal si cortamos el texto, para que no colisione con la flecha:
<img width="409" alt="screen shot 2018-04-30 at 9 32 28 pm" src="https://user-images.githubusercontent.com/7244247/39457764-0c01ff9e-4cbe-11e8-870b-85c5ae9482e6.png">
Esto arreglaría cualquier selector nativo sin preocuparnos por el tamaño

**Comment by FranMonteverde** [comment]
@testica go ahead bro. Válida tu solución
