### ISSUE TITLE
Seleccionador de Moneda e Idioma en Mobile

### ISSUE THREAD

**Issue by testica** [zomoz/reportes#7]
## Estoy reportando...

- [ ] Error 
- [x] Mejora 
- [ ] Métrica 
- [ ] Otro... Por favor descríbelo:

## Comportamiento actual

Cambiaron los estilos de estos modales ya que las opciones estaban muy pegadas unas a las otras y era difícil seleccionar

## Comportamiento esperado

![image](https://user-images.githubusercontent.com/7244247/38946774-81057254-4308-11e8-9d6f-e38cd78cf63d.png)

Links de zeplin:
[Desktop](https://zpl.io/2Zg5zKL)
[Mobile](https://zpl.io/VkDnLEg)
## ¿Qué impacto tiene en el negocio este reporte? 

- [ ] Bloqueante 
- [x] Impacto nivel 3 
- [ ] Impacto nivel 2 
- [ ] Impacto nivel 1

**Comment by jcao02** [comment]
Se arregló en zomoz/web#1633
